# Project Information
site_name: AI Wiki
site_description: AI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛
site_author: AI Wiki Team
site_url: https://hai5g.cn/aiwiki
strict: true

# Repository
repo_name: 'aiwiki'
repo_url: 'https://github.com/myourdream/aiwiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2019 AI Wiki Team'

# Contents
nav:
  - 简介:
    - Getting Started: index.md
    - AI学习路线: intro/AI学习路线.md
    - AI 赛事与赛制: intro/mode.md
    - ICPC/CCPC 赛事与赛制: intro/icpc.md
    - 学习资源: intro/resources.md
    - 常见错误: intro/common-mistakes.md
    - 常见技巧: intro/common-tricks.md
    - 非传统题: intro/non-traditional.md
    - 工具软件:
      - 评测工具: intro/judgers.md
      - 编辑工具: intro/editors.md
      - WSL (Windows 10): intro/wsl.md
      - Special Judge: intro/spj.md
      - Testlib:
        - Testlib 简介: intro/testlib/index.md
        - 通用: intro/testlib/general.md
        - Generator: intro/testlib/generator.md
        - Validator: intro/testlib/validator.md
        - Interactor: intro/testlib/interactor.md
        - Checker: intro/testlib/checker.md
    - Docker 部署: intro/docker-deploy.md
    - 关于本项目: intro/about.md
    - F.A.Q.: intro/faq.md
  - Machine Learning:
    - 简介: Coursera_ML_AndrewNg/markdown/SUMMARY.md
    - 数学基础: Coursera_ML_AndrewNg/markdown/math.md
    - week1: Coursera_ML_AndrewNg/markdown/week1.md
    - week2: Coursera_ML_AndrewNg/markdown/week2.md
    - week3: Coursera_ML_AndrewNg/markdown/week3.md
    - week4: Coursera_ML_AndrewNg/markdown/week4.md
    - week5: Coursera_ML_AndrewNg/markdown/week5.md
    - week6: Coursera_ML_AndrewNg/markdown/week6.md
    - week7: Coursera_ML_AndrewNg/markdown/week7.md
    - week8: Coursera_ML_AndrewNg/markdown/week8.md
    - week9: Coursera_ML_AndrewNg/markdown/week9.md
    - week10: Coursera_ML_AndrewNg/markdown/week10.md
  - 深度学习500问:
    - 简介: qa500/index.md
    - 目录: qa500/content.md
    - 第一章_数学基础: qa500/ch01_math/ch01_math.md
    - 第二章_机器学习基础: qa500/ch02_机器学习基础/第二章_机器学习基础.md
    - 第三章_深度学习基础: qa500/ch03_深度学习基础/第三章_深度学习基础.md
    - 第四章_经典网络: qa500/ch04_经典网络/第四章_经典网络.md
    - 第五章 卷积神经网络（CNN）: qa500/ch05_卷积神经网络(CNN)/第五章 卷积神经网络（CNN）.md
    - 第六章_循环神经网络(RNN): qa500/ch06_循环神经网络(RNN)/第六章_循环神经网络(RNN).md
    - 第七章_生成对抗网络(GAN): qa500/ch07_生成对抗网络(GAN)/ch7.md
    - 第八章_目标检测: qa500/ch08_目标检测/第八章_目标检测.md
    - 第九章_图像分割: qa500/ch09_图像分割/第九章_图像分割.md
    - 第十章_强化学习: qa500/ch10_强化学习/第十章_强化学习.md
    - 第十一章_迁移学习: qa500/ch11_迁移学习/第十一章_迁移学习.md
    - 第十二章_网络搭建及训练: qa500/ch12_网络搭建及训练/第十二章_网络搭建及训练.md
    - 第十三章_优化算法: qa500/ch13_优化算法/第十三章_优化算法.md
    - 第十四章_超参数调整: qa500/ch14_超参数调整/第十四章_超参数调整.md
    - 第十五章_异构运算、GPU及框架选型: qa500/ch15_GPU和框架选型/第十五章_异构运算、GPU及框架选型.md
    - 第十六章_NLP: qa500/ch16_自然语言处理(NLP)/第十六章_NLP.md
    - 第十七章_模型压缩、加速及移动端部署: qa500/ch17_模型压缩、加速及移动端部署/第十七章_模型压缩、加速及移动端部署.md
    - 第十八章_后端架构选型、离线及实时计算: qa500/ch18_后端架构选型、离线及实时计算/第十八章_后端架构选型、离线及实时计算.md
    - 第十八章_后端架构选型及应用场景: qa500/ch18_后端架构选型及应用场景/第十八章_后端架构选型及应用场景.md
  - 经典算法:
    - 动态规划部分简介: dp/index.md
    - 记忆化搜索: dp/memo.md
    - 背包 DP: dp/knapsack.md
    - 区间 DP: dp/interval.md
    - DAG 上的 DP: dp/dag.md
    - 树形 DP: dp/tree.md
    - 状压 DP: dp/state.md
    - 数位 DP: dp/number.md
    - 插头 DP: dp/plug.md
    - DP 优化:
      - 二进制分组解多重背包: dp/optimizations/binary-knapsack.md
      - 单调队列/单调栈优化: dp/optimizations/monotonous-queue-stack.md
      - 斜率优化: dp/optimizations/convex-hull-optimization.md
      - 四边形不等式优化: dp/optimizations/knuth-yao-quadrangle-inequality.md
      - 状态设计优化: dp/optimizations/state-optimization.md
    - 其它 DP 方法: dp/misc.md
  - 集成学习算法:
    - 字符串部分简介: string/index.md
    - 标准库: string/lib-func.md
    - 字符串匹配: string/match.md
    - 哈希: string/hash.md
    - 前缀函数与 KMP 算法: string/prefix-function.md
    - 字典树 (Trie): string/trie.md
    - 回文自动机: string/pam.md
    - 后缀数组 (SA): string/sa.md
    - AC 自动机: string/ac-automaton.md
    - 后缀自动机 (SAM): string/sam.md
    - 后缀树: string/suffix-tree.md
    - Manacher: string/manacher.md
    - 最小表示法: string/minimal-string.md
    - Z 函数（扩展 KMP）: string/z-function.md
  - CNN:
    - 数学部分简介: math/index.md
    - 进制: math/base.md
    - 位运算: math/bit.md
    - 高精度: math/bignum.md
    - 快速幂: math/quick-pow.md
    - 整除及其性质:
      - 素数: math/prime.md
      - 最大公约数: math/gcd.md
      - 欧拉函数: math/euler.md
      - 筛法: math/sieve.md
      - 费马小定理: math/fermat.md
    - 同余方程相关:
      - 裴蜀定理: math/bezouts.md
      - 乘法逆元: math/inverse.md
      - 线性同余方程: math/linear-equation.md
      - 中国剩余定理: math/crt.md
      - BSGS: math/bsgs.md
      - 原根: math/primitive-root.md
    - 线性代数:
      - 矩阵: math/matrix.md
      - 高斯消元: math/gauss.md
      - 线性基: math/basis.md
    - 复数: math/complex.md
    - 分段打表: math/dictionary.md
    - 数论函数相关:
      - 莫比乌斯反演: math/mobius.md
      - 杜教筛: math/du-sieves.md
    - 多项式:
      - 多项式部分简介: math/poly/intro.md
      - 拉格朗日插值: math/poly/lagrange-poly.md
      - 快速傅里叶变换: math/poly/fft.md
      - 快速数论变换: math/poly/ntt.md
      - 快速沃尔什变换: math/poly/fwt.md
      - 多项式求逆: math/poly/inv.md
      - 多项式开方: math/poly/sqrt.md
      - 多项式除法|取模: math/poly/div-mod.md
      - 多项式对数函数|指数函数: math/poly/ln-exp.md
      - 多项式牛顿迭代: math/poly/newton.md
      - 多项式多点求值|快速插值: math/poly/multipoint-eval-interpolation.md
      - 多项式三角函数: math/poly/tri-func.md
      - 多项式反三角函数: math/poly/inv-tri-func.md
    - 组合数学:
      - 排列组合: math/combination.md
      - 卡特兰数: math/catalan.md
      - 斯特林数: math/stirling.md
      - 康托展开: math/cantor.md
      - 容斥原理: math/inclusion-exclusion-principle.md
      - 抽屉原理: math/drawer-principle.md
    - 概率 & 期望: math/expectation.md
    - 置换群: math/permutation-group.md
    - 数值积分: math/integral.md
    - 线性规划: math/linear-programming.md
    - 博弈论: math/game-theory.md
    - 杂项: math/misc.md
  - RNN:
    - 数据结构部分简介: ds/index.md
    - STL:
      - STL 简介: ds/stl.md
      - vector: ds/stl/vector.md
      - priority_queue: ds/stl/priority_queue.md
      - map: ds/stl/map.md
      - bitset: ds/stl/bitset.md
    - pb_ds:
      - pb_ds 简介: ds/pb-ds/index.md
      - __gnu_pbds::priority_queue: ds/pb-ds/priority-queue.md
    - 栈: ds/stack.md
    - 队列: ds/queue.md
    - 链表: ds/linked-list.md
    - 哈希表: ds/hash.md
    - 并查集: ds/dsu.md
    - 堆:
      - 堆简介: ds/heap.md
      - 二叉堆: ds/binary-heap.md
      - 配对堆: ds/pairing-heap.md
    - 块状数据结构:
      - 分块思想: ds/square-root-decomposition.md
      - 块状链表: ds/block-list.md
      - 块状数组: ds/block-array.md
      - 树分块: ds/tree-decompose.md
    - 单调栈: ds/monotonous-stack.md
    - 单调队列: ds/monotonous-queue.md
    - 倍增: ds/sparse-table.md
    - 树状数组: ds/bit.md
    - 线段树: ds/segment.md
    - 划分树: ds/dividing.md
    - 平衡树:
      - 二叉搜索树简介: ds/bst.md
      - Treap: ds/treap.md
      - Splay: ds/splay.md
      - WBLT: ds/wblt.md
      - Size Balanced Tree: ds/sbt.md
      - AVL 树: ds/avl.md
      - 替罪羊树: ds/scapegoat.md
    - 树套树:
      - 线段树套线段树: ds/seg-in-seg.md
      - 平衡树套线段树: ds/seg-in-balanced.md
      - 线段树套平衡树: ds/balanced-in-seg.md
      - 树状数组套主席树: ds/persistent-in-bit.md
    - K-Dtree: ds/k-dtree.md
    - 可持久化数据结构:
      - 可持久化数据结构简介: ds/persistent.md
      - 可持久化线段树: ds/persistent-seg.md
      - 可持久化块状数组: ds/persistent-block-array.md
      - 可持久化平衡树: ds/persistent-balanced.md
      - 可持久化字典树: ds/persistent-trie.md
    - 珂朵莉树: ds/odt.md
    - Link Cut Tree: ds/lct.md
    - Euler Tour Tree: ds/ett.md
  - GAN:
    - 图论部分简介: graph/index.md
    - 图论基础: graph/basic.md
    - 图的遍历: graph/traverse.md
    - 树上问题:
      - 树基础: graph/tree-basic.md
      - 最近公共祖先: graph/lca.md
      - DFS 序: graph/dfs-order.md
      - 树的其他问题: graph/tree-misc.md
      - 树哈希: graph/tree-hash.md
      - 树链剖分: graph/heavy-light-decomposition.md
      - 树分治: graph/tree-divide.md
      - 动态树分治: graph/dynamic-tree-divide.md
      - 虚树: graph/virtual-tree.md
      - 树上启发式合并: graph/dsu-on-tree.md
    - 矩阵树定理: graph/matrix-tree.md
    - 有向无环图: graph/dag.md
    - 拓扑排序: graph/topo.md
    - 最小生成树: graph/mst.md
    - 最小树形图: graph/mdst.md
    - 最短路: graph/shortest-path.md
    - 差分约束: graph/differential-constraints.md
    - k 短路: graph/kth-path.md
    - 连通性相关:
      - 强连通分量: graph/scc.md
      - 双连通分量: graph/bcc.md
      - 割点和桥: graph/bridge.md
      - 2-SAT: graph/2-sat.md
    - 欧拉图: graph/euler.md
    - 哈密顿图: graph/hamilton.md
    - 二分图: graph/bi-graph.md
    - 最小环: graph/min-circle.md
    - 平面图: graph/planar.md
    - 图的着色: graph/color.md
    - 网络流:
      - 网络流简介: graph/flow.md
      - 拆点: graph/flow/node.md
      - 最大流: graph/flow/max-flow.md
      - 最小割: graph/flow/min-cut.md
      - 费用流: graph/flow/min-cost.md
      - 上下界网络流: graph/flow/bound.md
    - 图论杂项: graph/misc.md
  - 计算机视觉:
    - 计算几何部分简介: geometry/index.md
    - 二维计算几何基础: geometry/2d.md
    - 三维计算几何基础: geometry/3d.md
    - 距离: geometry/distance.md
    - Pick 定理: geometry/pick.md
    - 三角剖分: geometry/triangulation.md
    - 凸包: geometry/convex-hull.md
    - 扫描线: geometry/scanning.md
    - 旋转卡壳: geometry/rotating-calipers.md
    - 半平面交: geometry/half-plane-intersection.md
    - 平面最近点对: geometry/nearest-points.md
    - 计算几何杂项: geometry/magic.md
  - NLP:
    - 杂项简介: misc/index.md
    - 读入、输出优化: misc/io.md
    - 复杂度: misc/complexity.md
    - 离散化: misc/discrete.md
    - 离线算法:
      - 离线算法简介: misc/offline.md
      - CDQ 分治: misc/cdq-divide.md
      - 莫队算法: misc/mo-algo.md
    - 分数规划: misc/fractional-programming.md
    - 随机化:
      - 随机函数: misc/random.md
      - 爬山算法: misc/hill-climbing.md
      - 模拟退火: misc/simulated-annealing.md
      - 随机增量法: misc/random-incremental.md
    - 悬线法: misc/largest-matrix.md
    - 计算理论基础: misc/cc-basic.md
    - 字节顺序: misc/endianness.md
  - 推荐系统:
    - 杂项简介: misc/index.md
    - 读入、输出优化: misc/io.md
    - 复杂度: misc/complexity.md
    - 离散化: misc/discrete.md
    - 离线算法:
      - 离线算法简介: misc/offline.md
      - CDQ 分治: misc/cdq-divide.md
      - 莫队算法: misc/mo-algo.md
    - 分数规划: misc/fractional-programming.md
    - 随机化:
      - 随机函数: misc/random.md
      - 爬山算法: misc/hill-climbing.md
      - 模拟退火: misc/simulated-annealing.md
      - 随机增量法: misc/random-incremental.md
    - 悬线法: misc/largest-matrix.md
    - 计算理论基础: misc/cc-basic.md
    - 字节顺序: misc/endianness.md
  - 关于: about.md
# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'AI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''

extra_javascript:
  - 'https://cdn.jsdelivr.net/gh/ethantw/Han@3.3.0/dist/han.min.js'
  - '_static/js/extra.js?v=10'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - 'https://cdn.jsdelivr.net/npm/ah@1.5.0/han.min.css'
  - '_static/css/extra.css?v=11'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
