# Project Information
site_name: AI Wiki
site_description: AI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛
site_author: AI Wiki Team
site_url: https://hai5g.cn/aiwiki
strict: true

# Repository
repo_name: 'aiwiki'
repo_url: 'https://github.com/myourdream/aiwiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2019 AI Wiki Team'

# Contents
nav:
  - 简介:
    - Getting Started: index.md
    - AI学习路线1: intro/AI学习路线.md
    - AI学习路线2: intro/ai-roadmap/ai-union-201904/README.md
    - AI 路线图v0.1: intro/ai-roadmap/v0.1/README.md
    - AI 路线图v0.2: intro/ai-roadmap/v0.2/README.md
    - ApacheCN 人工智能知识树: intro/ai-roadmap/v1.0/README.md
    - 工具软件:
      - 评测工具: intro/judgers.md
      - 编辑工具: intro/editors.md
      - WSL (Windows 10): intro/wsl.md
      - Special Judge: intro/spj.md
      - Testlib:
        - Testlib 简介: intro/testlib/index.md
        - 通用: intro/testlib/general.md
        - Generator: intro/testlib/generator.md
        - Validator: intro/testlib/validator.md
        - Interactor: intro/testlib/interactor.md
        - Checker: intro/testlib/checker.md
    - Docker 部署: intro/docker-deploy.md
    - 关于本项目: intro/about.md
    - F.A.Q.: intro/faq.md
  - 机器学习:
    - 简介: Coursera_ML_AndrewNg/README.md
    - 目录: Coursera_ML_AndrewNg/markdown/SUMMARY.md
    - 数学基础: Coursera_ML_AndrewNg/markdown/math.md
    - week1: Coursera_ML_AndrewNg/markdown/week1.md
    - week2: Coursera_ML_AndrewNg/markdown/week2.md
    - week3: Coursera_ML_AndrewNg/markdown/week3.md
    - week4: Coursera_ML_AndrewNg/markdown/week4.md
    - week5: Coursera_ML_AndrewNg/markdown/week5.md
    - week6: Coursera_ML_AndrewNg/markdown/week6.md
    - week7: Coursera_ML_AndrewNg/markdown/week7.md
    - week8: Coursera_ML_AndrewNg/markdown/week8.md
    - week9: Coursera_ML_AndrewNg/markdown/week9.md
    - week10: Coursera_ML_AndrewNg/markdown/week10.md
  - 深度学习500问:
    - 简介: qa500/index.md
    - 目录: qa500/content.md
    - 第一章_数学基础: qa500/ch01_math/ch01_math.md
    - 第二章_机器学习基础: qa500/ch02_机器学习基础/第二章_机器学习基础.md
    - 第三章_深度学习基础: qa500/ch03_深度学习基础/第三章_深度学习基础.md
    - 第四章_经典网络: qa500/ch04_经典网络/第四章_经典网络.md
    - 第五章 卷积神经网络（CNN）: qa500/ch05_卷积神经网络(CNN)/第五章 卷积神经网络（CNN）.md
    - 第六章_循环神经网络(RNN): qa500/ch06_循环神经网络(RNN)/第六章_循环神经网络(RNN).md
    - 第七章_生成对抗网络(GAN): qa500/ch07_生成对抗网络(GAN)/ch7.md
    - 第八章_目标检测: qa500/ch08_目标检测/第八章_目标检测.md
    - 第九章_图像分割: qa500/ch09_图像分割/第九章_图像分割.md
    - 第十章_强化学习: qa500/ch10_强化学习/第十章_强化学习.md
    - 第十一章_迁移学习: qa500/ch11_迁移学习/第十一章_迁移学习.md
    - 第十二章_网络搭建及训练: qa500/ch12_网络搭建及训练/第十二章_网络搭建及训练.md
    - 第十三章_优化算法: qa500/ch13_优化算法/第十三章_优化算法.md
    - 第十四章_超参数调整: qa500/ch14_超参数调整/第十四章_超参数调整.md
    - 第十五章_异构运算、GPU及框架选型: qa500/ch15_GPU和框架选型/第十五章_异构运算、GPU及框架选型.md
    - 第十六章_NLP: qa500/ch16_自然语言处理(NLP)/第十六章_NLP.md
    - 第十七章_模型压缩、加速及移动端部署: qa500/ch17_模型压缩、加速及移动端部署/第十七章_模型压缩、加速及移动端部署.md
    - 第十八章_后端架构选型、离线及实时计算: qa500/ch18_后端架构选型、离线及实时计算/第十八章_后端架构选型、离线及实时计算.md
    - 第十八章_后端架构选型及应用场景: qa500/ch18_后端架构选型及应用场景/第十八章_后端架构选型及应用场景.md
  - 统计学习:
    - 简介: lihang/README.md
    - 统计学习及监督学习概论: lihang/CH01/README.md
    - 感知机: lihang/CH02/README.md
    - K近邻法: lihang/CH03/README.md
    - 朴素贝叶斯法: lihang/CH04/README.md
    - 决策树: lihang/CH05/README.md
    - 逻辑斯蒂回归与最大熵模型: lihang/CH06/README.md
    - 支持向量机: lihang/CH07/README.md
    - 提升方法: lihang/CH08/README.md
    - EM算法及其推广: lihang/CH09/README.md
    - 隐马尔可夫模型: lihang/CH10/README.md
    - 条件随机场: lihang/CH11/README.md
    - 监督学习方法总结: lihang/CH12/README.md
    - 无监督学习概论: lihang/CH13/README.md
    - 聚类方法: lihang/CH14/README.md
    - 无监督学习方法总结: lihang/CH22/README.md
  - Sklearn与TensorFlow:
    - 简介: hands-on-ml-zh/README.old.md
    - 前言: hands-on-ml-zh/docs/0.前言.md
    - 机器学习概览: hands-on-ml-zh/docs/1.机器学习概览.md
    - 一个完整的机器学习项目: hands-on-ml-zh/docs/2.一个完整的机器学习项目.md
    - 分类: hands-on-ml-zh/docs/3.分类.md
    - 训练模型: hands-on-ml-zh/docs/4.训练模型.md
    - 支持向量机: hands-on-ml-zh/docs/5.支持向量机.md
    - 决策树: hands-on-ml-zh/docs/6.决策树.md
    - 集成学习和随机森林: hands-on-ml-zh/docs/7.集成学习和随机森林.md
    - 启动并运行_TensorFlow: hands-on-ml-zh/docs/9.启动并运行_TensorFlow.md
    - 人工神经网络介绍: hands-on-ml-zh/docs/10.人工神经网络介绍.md
    - 训练深层神经网络: hands-on-ml-zh/docs/11.训练深层神经网络.md
    - 设备和服务器上的分布式_TensorFlow: hands-on-ml-zh/docs/12.设备和服务器上的分布式_TensorFlow.md
    - 卷积神经网络: hands-on-ml-zh/docs/13.卷积神经网络.md
    - 循环神经网络: hands-on-ml-zh/docs/14.循环神经网络.md
    - 自编码器: hands-on-ml-zh/docs/15.自编码器.md
    - 强化学习: hands-on-ml-zh/docs/16.强化学习.md
    - B.机器学习项目清单: hands-on-ml-zh/docs/B.机器学习项目清单.md
    - C.SVM_对偶问题: hands-on-ml-zh/docs/C.SVM_对偶问题.md
    - D.自动微分: hands-on-ml-zh/docs/D.自动微分.md
  - Mastery博客:
    - 简介: ml-mastery-zh/README.md
    - XGBoost: ml-mastery-zh/docs/xgboost/SUMMARY.md
    - 深度学习（Keras）: ml-mastery-zh/docs/dl-keras/SUMMARY.md
# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'AI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''

extra_javascript:
  - 'https://cdn.jsdelivr.net/gh/ethantw/Han@3.3.0/dist/han.min.js'
  - '_static/js/extra.js?v=10'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - 'https://cdn.jsdelivr.net/npm/ah@1.5.0/han.min.css'
  - '_static/css/extra.css?v=11'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
